### ISSUE TITLE
Display of variables with both numeric and character data is not correct

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaLoadingIssues#1]
Example: India ICEMR Behavior Cross-sectional study has variables like ITN bednet count that have numeric values plus a value of "Don't know". Since there were so few values that the variable would display as categorical anyway, we opted to leave in the "Don't know" value. However, on the qa site, most of the data is disappearing, leaving only the "Don't know" value. First screenshot below shows the live site, the second shows the EDA site, which is only displaying the text values. 

![Screen Shot 2021-08-31 at 3 09 18 PM](https://user-images.githubusercontent.com/54597319/131569433-81eb8efe-464e-4454-8da4-4c206790c15b.png)

![Screen Shot 2021-08-31 at 3 09 29 PM](https://user-images.githubusercontent.com/54597319/131569480-a060540a-8ed1-4bea-b2f6-acbb613efcc2.png)

**Comment by jaycolin** [comment]
This issue has been resolved; if found in other studies, it will be resolved as they are being reloaded.
