### ISSUE TITLE
Show units for variables that are strings

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaLoadingIssues#10]
Ex: India ICEMR Behavior cross-sectional study has a number of variables (Transit time to health facility, 'Time from fever onset to treatment seeking', Time from malaria test until treatment started; Proposed time to seek malaria treatment) that have units loaded which do not display. Presumably this is because all of these variables contain values like "1-2" and "Don't know", and so are string rather that continuous. 

Please implement units in the label and data table even when data is string.

<img width="860" alt="Screen Shot 2021-10-04 at 4 15 19 PM" src="https://user-images.githubusercontent.com/54597319/135926050-b06bafa7-3f78-4424-801a-247d1496c3c9.png">
.

**Comment by steve-fischer-200** [comment]
sheena-  the recommended remedy is for outreach to add the units to any of these:
- the variable name
- the description
- the values
we're sorry that units don't work as you expected for strings, but... there are a number of reasons why they can't (without significant complications)

**Comment by SheenaTomko** [comment]
ClinEpi team decided that in cases like this we will add units to the end of the values and to the description. Closing this ticket
