### ISSUE TITLE
500 Internal Server Error: Wash B Kenya scatter plot with age

### ISSUE THREAD

**Issue by sweverschulman** [VEuPathDB/EdaLoadingIssues#12]
while qa-ing scatter plot. I ran across this error while plotting 'Length- or height-for-age z-score, using median stature' on the x and 'age' using a scatterplot. I encountered the following error: 500 Internal Server Error {"status":"server-error","message":"Unable to fetch all required data","requestId":"3rXrk8efBkHBvQzzWvAUpA"}

<img width="946" alt="Screen Shot 2021-10-06 at 3 04 19 PM" src="https://user-images.githubusercontent.com/62298921/136266874-c321c36e-b241-430b-9db0-f0d5e1753d7d.png">
 y

**Comment by jaycolin** [comment]
List of currently loaded multi-valued variables here:
https://docs.google.com/spreadsheets/d/1XuU7fEQ5qhg5U6mRDE-cpxz3ewtyWZN4nC9vZZi9BSY/edit#gid=1325300712
Please make notes if any action is needed

**Comment by ryanrdoherty** [comment]
@jaycolin Does this mean you have a TODO to populate the column with "1" for all those columns?  Is this a DB patch or will you reload the affected studies?

**Comment by jaycolin** [comment]
@ryanrdoherty Outreach will update the spreadsheet as needed. This was a bug in the loading plugin, which is fixed now, but I will have to reload all studies

**Comment by SheenaTomko** [comment]
This was fixed with Jay's reload. Closing this ticket
