### ISSUE TITLE
Variable values are "0 days", "1 day" "1-2 days" "3 days" ... "Don't know", but vocabulary is different

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#14]
Study: India ICEMR Behavior Cross-sectional
Variable: Proposed time to seek malaria treatment
Values in subsetting table: see title
vocabulary: "0", "1", "1-2", "3", ... "Don't know"

The discrepancy between values and vocabulary cause the histogram visualization to be empty

**Comment by jaycolin** [comment]
Patched

**Comment by bobular** [comment]
Thanks @jaycolin 

Just tested on on qa and it looks good.
![image](https://user-images.githubusercontent.com/308639/136962244-e3fdea24-f8a1-498f-a9cd-7983ed47f774.png)

I hope it really did need fixing (I tested using the dfalke-b back end and forgot to say).

Also this variable is now, correctly, barplot fodder, not histogram!

**Comment by SheenaTomko** [comment]
@bobular, why does the value of "Don't know" appear in the browse and subset tab but not the plot?

**Comment by bobular** [comment]
Oh, that's weird - I went to check again on qa and it's there now.  The numbers look the same (so no subsetting differences, as far as I can see)

![image](https://user-images.githubusercontent.com/308639/136985712-d22d1cec-b230-4f59-8fb0-f481695b39bd.png)

**Comment by jaycolin** [comment]
I hit the cache refresh URL, then "Don't know" appeared

**Comment by SheenaTomko** [comment]
Looks good to me now too. I just posted on another ticket I was qc'ing too that sometimes even if I refresh the cache using that URL and clear my own cache, I still see the bug when I first try and check
