### ISSUE TITLE
Collapse entity diagram in 1:1 relationships

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaLoadingIssues#19]
When data is loaded as 1:1 (like Community:Household, Household:Participant, Participant repeated measure:Sample, etc.), we want the entity diagram to collapse and variables to be considered within the same entity in the visualization tab and even the downloads, if possible.

Instead of always using the parent entity or the child entity as the one shown and labeled, may want to collapse in from the nodes. For example, when Community:Household are 1:1, we would show "Household" as the entity, but when Participant repeated measure:Sample is 1:1, we would show "Participant repeated measure" as the entity. "Participant" would always be seen as the central node

**Comment by danicahelb** [comment]
More information & example: 

Currently, we are loading communities as 1:1 with Households for studies that don’t have community variables other than “Country”. 
- If we didn’t do this, it would get loaded with a count of “1" for every Country, and the distribution table of Country data would be meaningless. 
- If people looked at “Country”, they can’t tell without subsetting the data how many households/participants come from each site

**Comment by steve-fischer-200** [comment]
just discussed with danica and sheena.  seems the best short term path, until we actually have cross study, is to collapse during data loading.

long term solution might be to also load a "cross-study" version of the study, with its own entity graph, and, when needed, tables for the expanded entities.   the other tables can be share with the original study.

(trying to achieve the collapsing dynamically in the subsetting service will be very complex, and is not a good path)

**Comment by SheenaTomko** [comment]
Decided to collapse 1:1 only communities and households and to do that at data loading by modifying the owl file. Closing this ticket
