### ISSUE TITLE
Bug: Variables that should be compatible are unavailable in certain plots

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/EdaLoadingIssues#2]
A couple of examples from GEMS1 Case control

Histogram: _Age_ is a continuous var and should be compatible with this plot, but is greyed out.

Scatter plot: _Weight_ is greyed out.

**Comment by SheenaTomko** [comment]
Closing this issue since it's a duplicate of https://github.com/VEuPathDB/EdaLoadingIssues/issues/3 and that issue is more up-to-date
