### ISSUE TITLE
Study summaries table should consistently use Title Case or Sentence case

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaLoadingIssues#24]
The columns on the study summaries table use different cases. Need to decide whether to use title or sentence case and apply to all:

![Screen Shot 2022-03-01 at 11 15 55 AM](https://user-images.githubusercontent.com/54597319/156216763-be631ae9-7114-4843-86e8-ad098b0fe154.png)

![Screen Shot 2022-03-01 at 11 16 09 AM](https://user-images.githubusercontent.com/54597319/156217006-e4a8fa79-a1ca-48fa-81cd-94f77f3db30d.png)

**Comment by steve-fischer-200** [comment]
The ontology is using Sentence case for variable names.  I think we should use the same here.

So, eg "Project Name" should be "Project name"

**Comment by steve-fischer-200** [comment]
i transferred this to EdaLoadingIssues because it is a DD team thing.  i assigned to @jaycolin figuring he'd know best how to route it

**Comment by danicahelb** [comment]
agree, we should use sentence case

"Eda Study ID" should be changed to "EDA study ID"

**Comment by jaycolin** [comment]
Fixed https://github.com/VEuPathDB/EbrcModelCommon/commit/5ca68255d7bb3235aeadd89391f3afbc04487d66

**Comment by SheenaTomko** [comment]
Test tomorrow after the site rebuilds overnight

**Comment by jaycolin** [comment]
Fix can be seen at integrate.clinepidb.org
![Screenshot from 2022-04-13 16-03-42](https://user-images.githubusercontent.com/8750198/163261229-ea6ed0b4-934d-41f6-acb6-93305aa8c7ad.png)

**Comment by jaycolin** [comment]
Missed a couple  of labels

**Comment by jaycolin** [comment]
Fixed a few more
https://github.com/VEuPathDB/EbrcModelCommon/commit/14a8158a62fba9a751ef38a6b7c2006abfd7f874

**Comment by SheenaTomko** [comment]
@jaycolin most columns now look great, there are just a few left with issues. 

total_number used to appear as "Total number". Can you check what happened there? And then also change "Release # and Date" -> "Release # and date" and "Contact Institution" -> "Contact institution". Thanks!

<img width="301" alt="Screen Shot 2022-04-14 at 9 37 49 AM" src="https://user-images.githubusercontent.com/54597319/163414219-8abd42a0-115d-4bdc-8c5c-f008dfbcfe92.png">

**Comment by jaycolin** [comment]
Fixed Release number and institution.

**total_number** something Cristina is working on ... assigning to her.

**Comment by danicahelb** [comment]
@SheenaTomko and @aurreco-uga what is "Total number"? I think we need a more descriptive label here

**Comment by SheenaTomko** [comment]
That's a good question. My best guess is it's a column used behind the scenes for calculations since it has the same values as Total requests when there is >=1 request, is 0.5 when there are 0 requests, and is 0 when requests are N/A. @aurreco-uga can we hide this column from the web page and the download?

![Screen Shot 2022-04-19 at 10 42 39 AM](https://user-images.githubusercontent.com/54597319/164042833-81dc6cb6-08e3-4cce-b73a-30c30508d731.png)

**Comment by aurreco-uga** [comment]
what about the study info page
<img width="1094" alt="Screen Shot 2022-08-17 at 10 15 08 PM" src="https://user-images.githubusercontent.com/16354313/185278038-ab5b5003-d9f9-4ecc-87ac-964f9d158d97.png">
?

**Comment by aurreco-uga** [comment]
committed https://github.com/VEuPathDB/EbrcModelCommon/commit/930171dd86dc907bb3d855a7015656c22d881936

**Comment by SheenaTomko** [comment]
The updates are done on the study summaries table, but Cristina identified a related issue with the capitalization in the study characteristics table on the study details tab. I will make a separate ticket for that
