### ISSUE TITLE
Backend: Add binSlider specs to variable metadata

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#25]
The workflow determines optimal bin widths for use in the subset tab. It uses the plot.data R package to do this, which guarantees we remain consistent between the subset and viz tabs while improving performance. 

This issue is a proposal to do the same for the binSlider specs.

Currently, determining bin slider min, max and step values is done slightly differently for the subset and viz tabs, w similar but not identical logic existing in both plot.data and web-eda. This not only means that behavior is slightly different in the two places, but also that changes to that behavior have to be implemented in two places.

I didnt want to drop this into EdaLoadingIssues in case people wanted to discuss first.

**Comment by danicahelb** [comment]
this sounds reasonable, I don't think it needs to be discussed before implementing

**Comment by chowington** [comment]
Bit confused about the styling tag here, personally!

**Comment by d-callan** [comment]
Not sure we should try this for b57 given how many hands it has to pass through/ the number of related tickets it's likely to generate.

**Comment by d-callan** [comment]
do we know if @jaycolin has been made aware of this?

**Comment by danicahelb** [comment]
slack conversation with @jbrestel 

> That shouldn't be difficult to update the code but it will require rebuild all datasets ( or patching somehow but that is messy). I can make the code change in 58 but should rollout with the other things when we rebuild

**Comment by danicahelb** [comment]
the ticket for data dev is: https://redmine.apidb.org/issues/47693
this git ticket is a reminder to make sure the redmine ticket gets completed

**Comment by d-callan** [comment]
@bobular rightly pointed out that units (particularly for date variables for ex) may make this tricky. are we saying we need to determine the bin slider values for each possible unit in the workflow?

**Comment by bobular** [comment]
Thinking a bit more about this...

The loading-time binWidth annotations ensure that the default histograms in subsetting and visualization are binned the same way. However the binSlider min/max/step is calculated by the back end and displayed by the client on these default histograms. So there isn't really a need for load-time annotations, just consistent binSlider calculation logic from the two histogram endpoints (`histogram` and `distribution`)

The binSlider calculations also depend on the x-axis zoom, and there are complications with date units too, but the main issue is that the binSlider settings are dynamic and a single database annotation isn't going to have much mileage.

**Comment by bobular** [comment]
Discussed with @asizemore and @jbrestel and we decided to close this.

**Comment by SheenaTomko** [comment]
Nothing to qa here. Closing the corresponding redmine
