### ISSUE TITLE
Low-cardinality variables need a vocabulary in study metadata

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#27]
Came up during work on this ticket
https://github.com/VEuPathDB/web-eda/issues/914

b56 faceting will not show empty-data facets properly because there is no vocabulary.

**Comment by danicahelb** [comment]
also, when low cardinality variables are used in overlays, the legend for values is blank (see this example from GEMS) 
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/25450900/156678282-b4298e3b-522d-41fe-a76e-32ab158c5315.png">

**Comment by moontrip** [comment]
@danicahelb (and probably @d-callan) Yes indeed. The legend text/label relies on backend's data.name, but when using Overlay variable of `Household wealth index, categorical` (same to barplot and boxplot), I found that the data.name is empty string: not quite sure if it only happens to the variable. So it is a backend issue, I suppose.

**Comment by bobular** [comment]
> also, when low cardinality variables are used in overlays, the legend for values is blank (see this example from GEMS)

That's a different issue, already reported here: https://github.com/VEuPathDB/plot.data/issues/134

**Comment by d-callan** [comment]
this looks like it belongs in EdaLoadingIssues for jay.

looks like the workflow isnt generating the vocabulary for low cardinality continuous variables.

**Comment by jaycolin** [comment]
there's no specification on what you consider "low cardinality". Currently we never generate Vocabulary when dataShape = continuous. If we need to automatically handle this case, you will have to tell me what minimum or maximum number of values triggers generating Vocabulary. Also consider whether it is appropriate to handle this, or if the variable should be forced to string and handled as categorical. You can also force it to be handled as ordinal by adding ordinals in valueMap.txt. The only rule here is, if you do nothing, it will get dataShape = continuous and that means no vocabulary. All other dataShape values will generate a vocabulary.

**Comment by d-callan** [comment]
The vocabulary is needed for legend and axis tick labels, which typically allow up to 10 values. I'd say that's a fair cutoff for  'low cardinality'

**Comment by danicahelb** [comment]
this is happening broadly across studies, so it is more involved than patching a few terms. see this example from MALED

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/25450900/162855290-47497cbb-127b-4bfe-98f2-6ff87bd5ef22.png">

**Comment by jaycolin** [comment]
Reloading in progress with fix
https://github.com/VEuPathDB/ApiCommonData/commit/c3b4339f1c2212e62ffe50f7416a36bac357cbe6

**Comment by jaycolin** [comment]
Reloading done. I can't really check visualization but the original case EUPATH_0000143 wealth index categorical, now has vocabulary that was generated by workflow. All studies should now have vocabulary where cardinality <=10.

**Comment by SheenaTomko** [comment]
Something is still wrong here and I don't know who to assign it to. Tested on qa.clinepidb.org. When testing the examples given above, the plots are empty:
<img width="1104" alt="Screen Shot 2022-04-13 at 2 07 36 PM" src="https://user-images.githubusercontent.com/54597319/163252982-df99360d-62ee-4df3-ac6a-ce998503eb53.png">

<img width="1118" alt="Screen Shot 2022-04-13 at 2 09 56 PM" src="https://user-images.githubusercontent.com/54597319/163252990-ebadcdd4-f643-4979-a899-40b7d1c83cdc.png">

**Comment by jaycolin** [comment]
I have done a comprehensive audit. For all studies the vocabulary is present as required for variables <=0 (except studies currently reloading - PROMOTE, SHINE)
I'm closing this again but recommend re-opening the parent issue https://github.com/VEuPathDB/web-eda/issues/914

**Comment by SheenaTomko** [comment]
Moving this ticket to complete. I think this ongoing issue is appropriately documented in https://github.com/VEuPathDB/plot.data/issues/134
