### ISSUE TITLE
dataShape is being improperly set to 'ordinal' for non-ordinal categorical variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#28]
This is from the dfalke-b back end 
/eda-subsetting-service/studies/GEMSCC0003-1

One downside is that too many variables are available for the lineplot visualization.

```
{
	"7": {
		"id": "EUPATH_0000006",
		"parentId": "EUPATH_0000303",
		"providerLabel": "[\"F4A_FLOOR\",\"F7_FLOOR\"]",
		"displayName": "Floor material",
		"definition": "Predominant floor in the dwelling; assessed in the enrollment questionnaire for cases and controls.",
		"displayType": "default",
		"displayOrder": 1,
		"type": "string",
		"hideFrom": [],
		"dataShape": "ordinal",
		"vocabulary": [
			"Finished floor; carpet",
			"Finished floor; cement",
			"Finished floor; ceramic tile",
			"Finished floor; vinyl of asphalt strips",
			"Natural floor; dung",
			"Natural floor; earth/sand",
			"Other, specify",
			"Rudimentary floor; palm/bamboo",
			"Rudimentary floor; wood planks"
		],
		"distinctValuesCount": 9,
		"isTemporal": false,
		"isFeatured": false,
		"isMergeKey": false,
		"isMultiValued": false
	}
}
```

**Comment by danicahelb** [comment]
this seems to be a general issue across studies. For example, I can select "Cluster study arm" for the x-axis in line plots, even though this variable should be a **non-ordinal** categorical variable. 

it looks like dataShape is being incorrectly set across studies; categorical terms that do not have a valueOrder in the valueMap are being given dataShape of ‘ordinal’ when they should be ‘categorical’ 

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/25450900/162853899-db0c1780-bc48-4f36-abd8-c0f5d20ff7ae.png">

**Comment by jaycolin** [comment]
Reloading in progress with fix
https://github.com/VEuPathDB/ApiCommonData/commit/aeeb83adaf9d9a26e6d39f6c018e622be2e34afe

**Comment by jaycolin** [comment]
Fixed a bug
https://github.com/VEuPathDB/ApiCommonData/commit/aeeb83adaf9d9a26e6d39f6c018e622be2e34afe

**Comment by SheenaTomko** [comment]
This seems to be corrected now. Can no longer use Floor material in GEMS on the X-axis of a line plot or Cluster study arm in LLINEUP
