### ISSUE TITLE
Lineplot 500 response for certain categorical y variables

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#29]
GEMS1 - tested on qa today

No filters
Lineplot
x axis: Age group
y axis: **Breastfeeding status**
numerator/denominator: any valid combination

causes a 500 (and there is no obvious explanation in the HTTP header "stack trace")

I can't seem to find another variable in GEMS1 that causes the same error.

Not related obviously to https://github.com/VEuPathDB/EdaDataService/issues/169

**Comment by d-callan** [comment]
R is complaining its been passed a value of 'Not currently breastfed' as a claimed numerator and/or denominator value but cant actually find any such value. if i remove 'Not currently breastfed' from both numerator and denominator it works. i also dont see 'not currently breastfed' in the subset tab. i wonder if the vocabulary could possible be wrong somehow?

**Comment by jaycolin** [comment]
Incorrect line in valueMap.txt forces vocabulary to include the value that doesn't exist
`f4a_breastfed EUPATH_0011048  0 Not currently breastfed 1
`
I will patch the db and update this file

**Comment by jaycolin** [comment]
DB patched, valueMap.txt corrected. Now works on qa.restricted
