### ISSUE TITLE
Bug in scatter plot

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/EdaLoadingIssues#3]
GEMS1- Height vs. Weight scatter plot (using the full dataset -no filters) threw up an error:

<img width="1274" alt="Screen Shot 2021-09-07 at 9 56 54 AM" src="https://user-images.githubusercontent.com/67710160/132364758-c02261d4-7fd9-46fe-84f2-8d187d92ffb0.png">

**Comment by jaycolin** [comment]
Resolved by eliminating multiple values in 
https://redmine.apidb.org/issues/44112

**Comment by SheenaTomko** [comment]
Looks good
