### ISSUE TITLE
Geo variables are `hideFrom: [ ]`  (not hidden in variable pickers)

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#32]
In **SCORE Seasonal...** at least.

`GEOHASH 1`..`GEOHASH 6`, `latitude` and `longitude` are `hideFrom: [ ]` (empty array)

This means they are showing up in variable pickers.

![image](https://user-images.githubusercontent.com/308639/163168480-dc95717b-b8cf-4f1e-ad06-60f886bd9b5c.png)

Shouldn't they be `hideFrom: [ 'everywhere' ]`, or something like that?

IMO a b58 issue.

**Comment by nkittur-uga** [comment]
This issue has now been fixed in 3 SCORE studies by adding variable names (geohash1, geohash2 etc.) to the GEOHASH terms and reloading the studies. QA is complete. Closing the ticket.
