### ISSUE TITLE
WASH-b BNG terms under "Observation details" are multivalued, study needs to be reloaded with updated .owl

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#33]
I'm looking at the WASH-b Bangladesh study. I applied filters for Cluster study arm = "control" & "nutrition"

Age has this distribution in my subset
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/25450900/164093557-dc9e4098-6b9a-40d4-8e4b-558cf907e2a4.png">

But I cannot select "Age" as an x-axis variable in the scatter plot! (i have not set any other plot parameters)
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/25450900/164093727-fedfb1d2-8d53-48fa-9ff0-108a91b29257.png">

**Comment by danicahelb** [comment]
actually, i cannot select any terms under "observation details" even though i should be able to choose year and month as well as age
<img width="313" alt="image" src="https://user-images.githubusercontent.com/25450900/164094174-12a812ed-df8f-409f-8aaf-0f1968c496c0.png">

All other greyed out terms make sense

**Comment by danicahelb** [comment]
similarly, i cannot select these terms for the y-axis

**Comment by danicahelb** [comment]
actually... this may be due to these terms being multi-valued in this study. If this is the case, no need to change anything now. I intend to fix the multi-valued terms in a reload

**Comment by bobular** [comment]
Can confirm. The client requires the variable constraint `allowMultiValued` to be true if multi-valued variables are to pass the constraint filtering.  Default behaviour (in the absence of this constraint being provided) is to disallow all multi valued vars for all variables for all visualizations.

**Comment by dmfalke** [comment]
Should this issue be moved to a particular repo, or can it be closed?

**Comment by danicahelb** [comment]
@dmfalke its a data loading issue. I will assign the ticket to myself. Thanks

**Comment by danicahelb** [comment]
also, remove "blinded" from study arm definition

**Comment by danicahelb** [comment]
and update "is_temporal" annotations to allow terms to be used in individual-level line plots

**Comment by danicahelb** [comment]
study has been reloaded, multivalued issue has been fixed
