### ISSUE TITLE
Update annotation properties for ALL mbio studies

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaLoadingIssues#35]
<img width="1754" alt="Screen Shot 2022-04-06 at 10 38 56 AM" src="https://user-images.githubusercontent.com/11710234/162000636-cc3c46aa-67da-46f3-b112-0197fa5b2f77.png">

One example is Daily Baby. If a study is longitudinal, it should also have relevant repeated measures entities.

@wbazant I'm late in making this issue and not remembering our discussion well - are there any barriers to loading the data with this additional entity?

**Comment by wbazant** [comment]
This needs curation of ontology terms - look at ISA_2 field in the .owl: https://github.com/VEuPathDB/ApiCommonData/blob/master/Load/ontology/Microbiome/microbiome_human_only.owl 

It's currently either "Sample" or "Source". Putting repeated measures at its own level is one requirement for this.

Also, get an ontology term for "Participant repeated measure".

Then there are .xml files .e.g: https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/ISA/metadata/MBSTDY0021/BONUS.xml , that configure the entity graph. 

The xml says that source for human-only is actually a "Participant", the graph defines what the nodes and edges are, and so on. You can make these files with a master script - https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/scripts/make_eda_Xmls.pl.

Change all of that and reload, and you'll have a different entity graph!

**Comment by asizemore** [comment]
Thanks @wbazant !! Let me see if i can get this right:
- owl changes are for ontology team (Jie/John J)
- xml and pl changes would be for me? Or Jay? Or john b? Who would you recommend?

**Comment by wbazant** [comment]
> Who would you recommend?

Someone doing the role of a MicrobiomeDB data loader in the future!

If you, Jay and JohnB all applied to get this role, and I had to choose someone, I would probably really struggle. Likewise, if I had to pick either you, Jay, or JohnB, and appeal to them to pick up this role, I would probably also really struggle. Therefore, I would like to abstain from answering!


Yes, a MicrobiomeDB data loader can only obtain .owl changes by requesting them from the ontology team and describing very precisely what these changes should be.

There's an issue https://github.com/VEuPathDB/MicrobiomeWorkflow/issues/19 to put two studies on EDA, I will post to it describing what happens as I address the issue.

**Comment by asizemore** [comment]
Sounds good, thank you!

So is it correct that at least one of the two studies loaded in VEuPathDB/MicrobiomeWorkflow#19 will have these repeated measures?

**Comment by asizemore** [comment]
Transferring to EdaLoadingIssues

**Comment by asizemore** [comment]
Note for QA - please also check download files to make sure they're all good. We think solving this issue will also solve the odd formatting noted by @SheenaTomko in [this ticket](https://github.com/VEuPathDB/EdaLoadingIssues/issues/37)

**Comment by danicahelb** [comment]
@asizemore we need to standardize loading processes between clinepi & mbio.

annotation properties need to be filled out on a study-specific basis for ALL existing mbio studies (use same annotation properties as clinepi)

this will need to be fixed & all studies reloaded BEFORE mbio EDA can replace the current live site (WDK)

@sweverschulman will take the lead to:

- [ ] systematically fill out annotations for each study
- [ ] reload ALL mbio studies
- [ ] perform initial QA to ensure the web display matches her intentions / study design
- [ ] coordinate with @dpbisme to perform final QA 

This will fix longitudinal issues as well as other issues, so I am updating the title of this ticket & will link related tickets

GOAL: @sweverschulman should be able to get all studies updated before she goes on maternity leave

**Comment by danicahelb** [comment]
redmine ticket: https://redmine.apidb.org/issues/48002

**Comment by danicahelb** [comment]
There may be other tickets related to annotation property issues, but fixing the annotation props will fix all of these issues:

https://github.com/VEuPathDB/EdaLoadingIssues/issues/48

https://github.com/VEuPathDB/EdaLoadingIssues/issues/49

https://github.com/VEuPathDB/EdaLoadingIssues/issues/42

https://github.com/VEuPathDB/MicrobiomePresenters/issues/5

https://github.com/VEuPathDB/EdaLoadingIssues/issues/38

https://github.com/VEuPathDB/EdaLoadingIssues/issues/40

https://github.com/VEuPathDB/microbiomeComputations/issues/24

https://github.com/VEuPathDB/EdaLoadingIssues/issues/36

**Comment by asizemore** [comment]
> @sweverschulman will take the lead to ...

The list just keeps going. @sweverschulman is a hero.

**Comment by danicahelb** [comment]
move to b63, for when @sweverschulman is back from maternity leave

**Comment by danicahelb** [comment]
this will be fixed by: https://github.com/VEuPathDB/EdaNewIssues/issues/525
closing this ticket
