### ISSUE TITLE
splitUnitFromValue annotation for variables

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaLoadingIssues#38]
In the Preterm Infant Resistome II (WGS) study, the "Age at discharge", "Maternal age at birth", and "Postmenstrual age at sample collection" should be numbers with days/months/years as the units. For example, see [this Age](https://beta.clinepidb.org/ce.beta/app/workspace/analyses/DS_221d2bcac4/FagLY4k/variables/EUPATH_0000096/OBI_0001169) variable.

**Comment by wbazant** [comment]
This is an issue for all terms where splitUnitFromValue annotation was applied: see the list in https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/ISA/config/ontologyMappingsMicrobiome.xml.

In an overview: the sample detail file has values like "2 hours", and with a "splitUnitFromValue" annotation we remove the " hours" part and record it as a unit. Remarkably, we don't show that the variable is in hours on the live site.

Even more remarkably, it also doesn't seem to show up in ClinEpi. For example, here:
![Screenshot from 2022-05-09 10-04-03](https://user-images.githubusercontent.com/16976512/167427598-dcfa631e-7917-4b5e-b685-2a433a416fb1.png)
a "Study timepoint" variable is in months, but I can only guess / infer it from the variable description.

So I think the following plan is needed for this one:
- wait until EDA gets the technology for displaying annotated units, and it works for ClinEpi
- get a list of variables that have a "splitUnitFromValue" in the legacy ontologyMappingsMicrobiome.xml config
- annotate them in microbiome_human_only.owl however ClinEpi does this
- possibly write some code, I don't know
- ...
- ???
- get variables to show up correctly!

Showing up correctly would, in my opinion, mean that we're going from a variable name like "Delivery duration", and values like "2 hours" in a multipick, to "Delivery duration (hours)" showing nicely, and a numeric variable.

**Comment by wbazant** [comment]
Bonus: do something appropriate with the other functions, like enforceYesNoForBoolean. Copy the ClinEpi solution.

**Comment by wbazant** [comment]
next todo on this is probably: find out what clinepi is doing for units, and what plans to support them there are - I think they were a "phase 2" kind of thing

**Comment by asizemore** [comment]
@jaycolin does clinepi have variables like this that show up as "123 days" instead of the number 123? If yes, does the workflow have a way to split the number from the units?

**Comment by jaycolin** [comment]
No, we don't load values mixed with units (or if we do they are handled as strings/categorical variables and have no stats)

**Comment by asizemore** [comment]
ah okay cool. So to make sure i understand - if we wanted these variables to show up as numbers, we'd need to go clean the data (so remove all the "days") before sending it over to you for loading?

**Comment by jaycolin** [comment]
I see https://github.com/VEuPathDB/ApiCommonMetadataRepository/blob/master/ISA/config/ontologyMappingsMicrobiome.xml has the function to strip units; so that works for the value and you don't have to clean it. But I think the units should be defined in the ontology term (microbiome_human_only.owl) unitsLabel, unitsIRI. Though I don't think it is strictly required.

**Comment by danicahelb** [comment]
Annotation properties `unitLabel` & `unitIRI` need to be filled out for all terms requiring units, on a per-study basis

**Comment by danicahelb** [comment]
this will be fixed by https://github.com/VEuPathDB/EdaNewIssues/issues/525
closing this ticket
