### ISSUE TITLE
EDA: add all the other microbiome studies

### ISSUE THREAD

**Issue by wbazant** [VEuPathDB/EdaLoadingIssues#39]
Adding all other studies needs a new .owl. The status of this task as of early May is follows:

- Wojtek asked something related to making an .owl at an MBio meeting (what should the entities be called) to kickstart this
- Jie suggested there should be a meeting about it, also with ClinEpi
- Dan asked Jie to organise the meeting
- Jie asked Dan to pick a time

Then a few times Jie asked Dan if he can pick a time for the meeting, and Dan reiterated his commitment but didn't pick a time.

When you have the new .owl, add all the other studies - follow https://github.com/VEuPathDB/MicrobiomeWorkflow/issues/19 .

**Comment by asizemore** [comment]
This has been completed
