### ISSUE TITLE
GEMS1 in mbio: Age group should be ordinal

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/EdaLoadingIssues#43]
<img width="1700" alt="Screen Shot 2022-09-12 at 11 32 08 AM" src="https://user-images.githubusercontent.com/11710234/189695082-13145615-b271-4e59-b5e0-30ff5b815f1c.png">

Please make the Age group variable an ordinal variable with the bin labels in ascending order.

**Comment by sweverschulman** [comment]
@jaycolin has patched the study for this release and a generalized solution will be developed later.

**Comment by danicahelb** [comment]
Ok great. I'm closing this ticket.
I made this ticket for a generalized solution: https://github.com/VEuPathDB/EdaLoadingIssues/issues/45

**Comment by danicahelb** [comment]
looks good!


![Image](https://user-images.githubusercontent.com/25450900/206369889-31c73911-c3bc-46ae-8ed2-0e00cd715ac4.png)
