### ISSUE TITLE
Add linkages on ClinEpi & mbio sites for MAL-ED samples with microbiome data

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#44]
On ClinEpiDB, MAL-ED has the term `Microbiome analysis performed` (and 928 Peru samples have values of `yes`)

- we need to indicate that the 1091 samples used in Raman et al. have microbiome data associated with them (so map `Microbiome analysis performed` to `yes` for these samples)

On mbio, we use the term `ClinEpiDB sample ID` to indicate the identifier for samples on ClinEpi with microbiome data (see GEMS1 on mbio). Currently, MAL-ED does not contain this term.

- we need to add `ClinEpiDB sample ID` to the MAL-ED study on mbio
- we need to indicate the ClinEpi sample ID for the 1091 samples used in Raman et al. for values of `ClinEpiDB sample ID`
- we also need to indicate the ClinEpi sample ID for the 928 Peru samples with microbiome data for values of `ClinEpiDB sample ID`

**Comment by dmfalke** [comment]
Is there a good repo for this issue?

**Comment by danicahelb** [comment]
@dmfalke probably EdaLoadingIssues

**Comment by danicahelb** [comment]
I updated the conversion file so that `Microbiome analysis performed` is mapped to `yes` for the 1091 Raman mbio samples

I also added a new term to the conversion file for `MicrobiomeDB.org study` (EUPATH_0011881)
- 928 stool samples: `MAL-ED diarrhea`
- 1091 stool samples: `MAL-ED 2yr`

In file **221130_MALED_Raman_health_microbiome.csv**
- either `raman_sid` or `sid` is the identifier used on mbio site 
- you will need to map `sid` to the obfuscated version of the sample identifier (`Sample ID`) used on ClinEpi (ask @jaycolin)
- the obfuscated ClinEpi `Sample ID` is what should be mapped to the term `ClinEpi sample ID` on  the mbio site 

In file **200624_MALED_mapping_Griffin.csv**
- either `sample_alias` or `sid` is the identifier used on mbio site 
- you will need to map `sid` to the obfuscated version of the sample identifier (`Sample ID`) used on ClinEpi (ask @jaycolin)
- the obfuscated ClinEpi `Sample ID` is what should be mapped to the term `ClinEpi sample ID` on  the mbio site 

**221130_MALED_Raman_health_microbiome.csv** and updated version of **200624_MALED_mapping_Griffin.csv** can be found in manual delivery: `/eupath/data/EuPathDB/manualDelivery/ClinEpiDB/Gates/MAL-ED/phase3/2022-12/workspace/`

**Comment by jaycolin** [comment]
Done for mbio b61, QA at feature.microbiomedb.org

**Comment by danicahelb** [comment]
@jaycolin @sweverschulman For MAL-ED 2yr, do we know why only 1008 of the 1091 samples have ClinEpi IDs? (note that 928 samples in MAL-ED diarrhea have ClinEpi IDs, as expected)

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/25450900/205399889-cfa8d189-b1b3-4c19-bb83-f6f2126002ee.png">
