### ISSUE TITLE
mbio MALED diarrhea: structure of the dataset is incorrect!

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#49]
Similar issue as was found with MALED 2yr: [mbio MALED 2yr: structure of the dataset is incorrect! ](https://github.com/VEuPathDB/EdaLoadingIssues/issues/48)

MALED diarrhea study looked at microbiome in 928 stool samples collected longitudinally at 6, 12, 18 and 24 months from 271 participants

The dataset diagram does NOT account for longitudinal sample collection (ie, there are NO repeated measures)
<img width="906" alt="image" src="https://user-images.githubusercontent.com/25450900/206380261-b3a30fe8-a526-4bf8-9dcf-1bb289baa638.png">

"Age" is listed under "participant" and so we cannot tie the stool sample collections to any timepoints to indicate how things change over time

Also, anthropometry measurements are also listed under "participant" and are therefore not relevant to stool samples collected over time (including variables such as `LAZ at sampling` which implies LAZ and stool sample were collected on the same day!

I have not seen the original mbio data file, but can still tell that this study needs to be reloaded

**Comment by danicahelb** [comment]
Annotation property `repeated` needs to be evaluated for each variable in a longitudinal study

Annotation property `mergeKey` needs to be filled out for the timepoint variable

Sample IDs must be tied to a time point (date, age, etc)

**Comment by danicahelb** [comment]
looks good!

**Comment by cafferychen777** [comment]
Hello @danicahelb ,

I understand the concerns you've raised about the structure of the MALED diarrhea study dataset. If you're looking for a tool that can help you work with longitudinal microbiome data and effectively analyze repeated measures, I recommend exploring MicrobiomeStat. MicrobiomeStat is a versatile R package designed for precisely this type of analysis.

With MicrobiomeStat, you can easily account for longitudinal sample collection, perform various statistical analyses, and visualize how microbiome compositions change over time. It provides the necessary functionalities to handle repeated measures and make meaningful insights from your data.

You can find MicrobiomeStat on GitHub, where you'll also find documentation and examples to help you get started: [MicrobiomeStat on GitHub](https://github.com/cafferychen777/MicrobiomeStat)

I hope this helps you in your analysis. If you have any questions or need further assistance, feel free to reach out. 

Best regards,
