### ISSUE TITLE
mbio ontology: update parent for age & age group

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/EdaLoadingIssues#50]
In mbio, `age` and `age group` are under different parents (see gems1 example)
<img width="204" alt="image" src="https://user-images.githubusercontent.com/25450900/206370451-82bc07db-ca64-4a60-93a2-88554b224e10.png">

in clinepi, `age` and `age group` are both under parent observation details (see gems1 example)
<img width="282" alt="image" src="https://user-images.githubusercontent.com/25450900/206370612-1d8ce3d5-bfc3-46cd-9d13-bd4426e0b06f.png">

please update mbio ontology so that `age` falls under `observation details` instead of `demographics`

**Comment by SheenaTomko** [comment]
Note that we decided a few months ago to move "Age" to Demographics. The real change needed here is to move "Age group" to Demographics in all studies (ClinEpi and Mbio)

**Comment by jaycolin** [comment]
Patched in feature.microbiomedb.org so it will go out in b62

**Comment by SheenaTomko** [comment]
Nupur confirmed this looks good!
