### ISSUE TITLE
Update dataset cleaning process to generate proper IsaTab

### ISSUE THREAD

**Issue by steve-fischer-200** [VEuPathDB/EdaLoadingIssues#58]
Update the vectorbase cleaning scripts to no longer involve chado, and to generate the expected IsaTab.

This assumes that the data loading system can handle IsaTab, rather than IsaSimple

**Comment by bobular** [comment]
Working on this now with relevance to getting tick data processed regularly.

Revamping SAF (Simple Abundance Format, formerly known as PopBio Interchange Format) for a new era of unbridled possibility.

https://github.com/VEuPathDB/SimpleAbundanceFormat/

**Comment by bobular** [comment]
This is now in a usable state, but lacks documentation.

For this ticket to be closed, a clear understanding of what types of data the cleaning process applies to is needed.  Hopefully we can discuss tomorrow.

**Comment by bobular** [comment]
Documentation now exists here 
https://veupathdb.atlassian.net/wiki/spaces/TECH/pages/326205441/Preparing+PopBio+ISA-Tab+from+SAF2

It has been used in anger for the Maine ticks.

Sarah is nearly tooled up to use this processing route for future datasets.
