### ISSUE TITLE
Implement alphanumeric ordering for values 

### ISSUE THREAD

**Issue by SheenaTomko** [VEuPathDB/EdaLoadingIssues#6]
Example: India ICEMR cross-sectional study. First screenshot shows the qa site, second shows what it should be, which is on the live site. I think Dave mentioned needing to implement an alphanumeric package to achieve this

<img width="363" alt="Screen Shot 2021-09-17 at 3 12 13 PM" src="https://user-images.githubusercontent.com/54597319/133848028-b39c515e-de89-4220-8153-96d7d893885d.png">
<img width="319" alt="Screen Shot 2021-09-17 at 3 14 09 PM" src="https://user-images.githubusercontent.com/54597319/133848320-ff16cf3d-03d2-4099-8e38-5a7f39936f4d.png">

**Comment by dmfalke** [comment]
This is a data loading issue. The client uses the order defined in the `vocabulary` property.

**Comment by dmfalke** [comment]
I transferred the issue and removed assignments.

**Comment by moontrip** [comment]
> I transferred the issue and removed assignment

@dmfalke I saw your comment and was about to unassign myself but you already did 😄

**Comment by jaycolin** [comment]
Fixed

**Comment by SheenaTomko** [comment]
Looks good in studies that have been reloaded like PRISM2 and India ICEMR cross-sectional. Other studies like India ICEMR Meghalaya that still need to be reloaded still have the problem, but closing this issue here
