### ISSUE TITLE
Data: mega-study sample.specimen_count has some crazy values

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#60]
Not sure if this is real yet. 
Entity count requests are very slow and come back zero for the filter shown (so an easy way to figure out which study has this data is not available)

![image](https://user-images.githubusercontent.com/308639/234352771-2904e44f-5e22-4669-b590-c2880ca7989b.png)

**Comment by steve-fischer-200** [comment]
Please QA to confirm if these values are real or a bug

**Comment by bobular** [comment]
Highest values are only for Chironomidae - midges.  I believe they are real - possibly determined by weight, not counting - not closing without comment from @samrund and @SAK22

**Comment by bobular** [comment]
An option could be to disable the two studies

Non-mosquito surveillance, Northwest Mosquito and Vector Control District, in California, USA, 2014

and 2015

**Comment by bobular** [comment]
Left out and will be remediated with a new variable in subsequent release
https://redmine.apidb.org/issues/51969
VBP0000404 VBP0000405
