### ISSUE TITLE
mega-study: specimen count variable placement in variable tree is problematic

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/EdaLoadingIssues#61]
See screenshot from https://github.com/VEuPathDB/EdaLoadingIssues/issues/60 

Always shows up under blood meal assay

One time we loaded it recently, it didn't.

**Comment by steve-fischer-200** [comment]
owl file has been tweaked.  will test when new data is loaded

**Comment by bobular** [comment]
This will go away because there are now separate count variables for sample and assays
