### ISSUE TITLE
Map: Load fixed study-level vocabularies for species

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#64]
We need a variable, likely hidden, on presumably the study entity which can say per study what species that study was looking for. My understanding is that its entirely possible that some species were targets of the study, but were not found. so ideally this list reflects the publications intent, and not just the list of species with non-zero values we load.

**Comment by bobular** [comment]
In theory, yes, the intent/expectation to find species X should be independent of whether any species X were actually found.

However, in practice we're going to create that list of species from those observed within a study. Some multi-year multi-studies (one per year) ought to have those lists unioned but we will see how practical that is.

Do we actually have to load this data in the database? Is https://github.com/VEuPathDB/EdaDataService/issues/264 an on-the-fly version?  Or could that be done on-the-fly if we take the pragmatic approach of making the vocabulary from the observations, not the intentions?

If loaded in the database, was it a multi-valued variable, or a JSON array as a string?

**Comment by d-callan** [comment]
I had thought sam rund said we already knew the list of species searched for fr the old map and could 'just' load it.

The data service ticket was intended to use this  list we loaded and adjust it based on applied filters. Viz plugins could use that cached result to impute 0 for a given subset across both markers and floaters. 

Idk if I have a strong opinion about multivalued vs json, but might have a slight preference for json?

**Comment by bobular** [comment]
We can certainly do this for species. And also for sex, developmental stage etc? Well, maybe it's just those three. I'll have a think about it. If the back end could do it automatically that would help a lot.

**Comment by d-callan** [comment]
Sure. We could also consider revising my proposed annotations so that indicating the need for row dependent vocab ha three conditions: 1) not needed 2) in the db 3) figure it out backend. I can think on that some as well.

**Comment by d-callan** [comment]
iirc, we said we wouldnt be loading these, and instead always figure it out backend. im going to close this. someone can reopen if im wrong.
