### ISSUE TITLE
Map: Introduce new value for Sample Type to differentiate true pooled specimens

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#68]
We should make a new Sample Type to differentiate true pooled samples vs when assays were done on individuals but only summary statistics reported. discussed in map ux on May 4th 2023. see notes [here](https://veupathdb.atlassian.net/l/cp/DdrX21Lf).

**Comment by d-callan** [comment]
There was concern expressed today in the map ux call that a single sample might have multiple assays, and only some of those would represent mashed pools. Can someone, maybe @bobular, confirm if this is the case? it seems if it were, that this Sample Type term wouldnt make sense anyhow?

**Comment by bobular** [comment]
Yes, @d-callan,  pool samples currently represent both scenarios
* individual specimens were assayed but only summary results are reported
* genuinely mashed pools that were assayed once.

I can imagine that re-curating these will be a major headache.  What are the pros for doing this (and cons for not)?

**Comment by d-callan** [comment]
I think the major pro is that this becomes easier for users to realize and filter on. It's currently unclear that 'pool' doesn't represent a single sample type, which is misleading.

**Comment by bobular** [comment]
So something like 'aggregated [results] pool' and 'mashed pool'?
Obviously those aren't good enough to be user facing, but a start.

**Comment by bobular** [comment]
@samrund @SAK22 suggestions

longhand

* data aggregated from multiple individually assayed specimens
* single assay performed on pooled material from multiple specimens

short labels

* data-aggregated pool
* physically combined pool

???

**Comment by bobular** [comment]
Seems to me we have to step back a bit and categorise *all* the types of sample we have:

Sampling approach:
* unbiased, quantitative collection/sampling
* "biased" sampling (e.g. crowd science mailed-in ticks, or 100 mosquitoes of species A, B and C collected and tested for insecticide resistance, genotypes etc)

Sample size:
* single individuals
* pools of same species/sex*/stage* (* sex/stage optional)

Physical or abstract nature of the sample represented in the Sample entity.
* abstract: literature surveys assert presence of a species in location X at time Y via collection method(s) Z; the legacy "population" sample type represented this; the species of the sample is the main "data" here.
* abstract: species/sex/stage information that is inherited by child assays; so an IR assay on deltamethrin might be performed using 88 mosquitoes and a permethrin assay might be done on 77 mosquitoes. The samples sizes here are attached to/important for the *assay* not the sample (which is really just abstract).
* physical

Here's an attempt to give examples for the 8 combinations of these 3 binary traits.

| nature | sampling | quantity | examples and notes |
|--------|--------|--------|-----------|
| physical | unbiased | individual | surveillance data reported as individuals, assays could be done on individuals |
| physical | unbiased | multiple | surveillance data |
| physical | biased | individual | mail-in ticks |
| physical | biased | multiple |  none? |
| abstract | unbiased | individual | none? |
| abstract | unbiased | multiple | none? |
| abstract | biased | individual | none? |
| abstract | biased | multiple | 1. population presence from literature surveys <br/> 2. bio-material used for insecticide resistance assays; sample.specimen_count doesn't matter; assay.specimen_count is useful metadata |

**Comment by bobular** [comment]
What I'm hopefully getting at is that we'd only ever want to attempt to visualise specimen abundance for unbiased samples.

I still need to think about visualising assay variables (do you weight by sample.specimen_count or assay.specimen_count, both, or none?)

What would we do with, for example, showing male/female in donuts when there's a mix of sample types? I think it only makes sense to do the specimen count weighting when we have filtered to show just unbiased samples.

**Comment by bobular** [comment]
Almost makes you want to have separate megastudies...

**Comment by bobular** [comment]
Hi @d-callan 

How important is the value of the sample_type variable in the Plan D world if we assume that users can _by some means or other_ filter down to a subset that is Plan D friendly (presumably one that has values for the special count variable) ?

If they can do this filtering without the sample_type variable, I don't see why we'd need to re-curate this variable.

Or were Plan D service plugins going to contain hard-coded filters on sample_type? I doubt that's the way we'd go, right?

**Comment by bobular** [comment]
Also, let's assume I'm making a request to a Plan-D-friendly map-markers endpoint.

In pseudo-JSON, my request would be something like

```
{
  outputEntity: sample,
  overlayVariable: { entity: sample, variable sex },
  weightingVariable: { entity: sample, variable: unbiased_specimen_count }
}
``` 

Can I also assume that this will only return results for the samples with values for both of those variables?  (It won't fall over and die, or anything...)

**Comment by bobular** [comment]
> Hi @d-callan
> 
> How important is the value of the sample_type variable in the Plan D world if we assume that users can _by some means or other_ filter down to a subset that is Plan D friendly (presumably one that has values for the special count variable) ?
> 
> If they can do this filtering without the sample_type variable, I don't see why we'd need to re-curate this variable.
> 
> Or were Plan D service plugins going to contain hard-coded filters on sample_type? I doubt that's the way we'd go, right?

Steve and I discussed and we decided it would be clearer to users to have the sample types be more meaningful

**Comment by bobular** [comment]
Some analysis of **pathogen infection** assays. Notes for my benefit mainly.

In general there is either a count (number_of_input_specimens) for the sample or the assay, but not both. Here are two examples:

() means no number_of_input_specimens at that level (sample and assay)
(#) means there is a number_of_input_specimens

sample : pool (#) -> assay () -> infected yes/no  - study: Nevada 2008
sample : pool () -> assay (#) -> infected yes/no and %  - study: gold mine

Just 6 samples have a count for sample **and** pathogen assay specimen count. From one study: 2021-mishra-mandla "A study of malaria vector surveillance as part of the Malaria Elimination Demonstration Project in Mandla, Madhya Pradesh" VBP0000737
sample type is pool, sample.counts are >1.  sample.counts == assay.counts. **Curation mix-up.**  This is not unbiased sampling so sample.count should be null. 

All pathogen assays with prevalence also have assay.number_of_input_specimens (assay (#)) 
this applies to individuals and pools
all individuals have assay.number_of_input_specimens == 1

BUT not all assays with assay.number_of_input_specimens (and pathogen presence/absence) have prevalence. There are 7 studies that don't have prevalence. They are `2014-` to `2018-NWVCD-surveillance-viral` (e.g. "Mosquito viral surveillance, Northwest Mosquito and Vector Control District, in California, USA, 2014") and `2020-ndlille-cameroon` VBP0000683 ("Entomological indicators of malaria transmission and insecticide resistance profile of Anopheles gambiae at the early phase of irrigated rice farming in the forest area of central Cameroon") - these are examples of mashed pools with a single yes/no result. There's nothing wrong with this. See final comments at end of this comment.


Only one study has individuals with prevalence: "Host attraction and biting behaviour of Anopheles mosquitoes in South Halmahera, Indonesia" 2018-St-Laurent-Halmahera VBP0000241
All values for prevalence are 0 and 100

Decisions...
* how about two assay specimen count variables?
  - number of input specimens to quantitative assay
  - number of input specimens to qualitative assay
* assays with prevalence data would get the quantitative version
* the quantitative one would be a "Plan D" count variable
* presence/absence variables would never play in Plan D - they would only make sense reported as the number of assays. If the user wants to filter down to sample.type=individual then they can interpret the presence/absence numbers as individuals if they wish.

When we go wide, are we going to make 2x variables for each pathogen?
* presence/absence of pathogen X
* prevalence of pathogen X

Probably!

**Comment by bobular** [comment]
Similar analysis of **insecticide resistance** assays

Two studies have values for _both_ sample.count and assay.count:

1. 2017-chouaibou-kdr-cotedivoire - VBP0000191 - "First report of the East African kdr mutation in an Anopheles gambiae mosquito in Cote d?Ivoire"
2. 2017-sangba-ir-car - VBP0000168 - "Evidence of multiple insecticide resistance mechanisms in Anopheles gambiae populations in Bangui, Central African Republic"

In both cases the sample.count == sum(assay.count).  The sampling is not unbiased and so the sample.count should be disregarded.

Studies with sample.count and no assay.count?

Aside: There's no way to filter for "all insecticide assays", however the vast majority have a value for "insecticide" as you'd expect. The ones that don't are biochemical assays and the target pathway is part of the protocol (not yet available in EDA/SAM).

So from now on, these are the stats for "regular" IR assays (with a value for insecticide): total 15,571 assays, 206 studies

With sample.count: 2 studies, 46 assays. These will be the same as the above.

With assay.count: 169 (includes the 2 with both); 9909 assays.

Sample.type: 9 samples are **individuals**, from 2 studies. They are:

1. 2018-dia-arabiensis - VBP0000274 - "Insecticide resistance in Anopheles arabiensis populations from Dakar and its suburbs: role of target site and metabolic resistance mechanisms"
2. 2018-itokawa-albopictus - VBP0000370 - "First detection of a Vssc allele V1016G conferring a high level of insecticide resistance in Aedes albopictus collected from Europe (Italy) and Asia (Vietnam), 2016: a new emerging threat to controlling arboviral diseases"

But these have an astounding 2,216 assays!!

2,209 are from the 2018-dia-arabiensis study - assay.counts are all 1. Not sure yet what kinds of results these have. Note that this study also has samples of type=pool, which have regular >1 assay.counts.  The type=individual assay results all have %mortality of 0 or 100.  Note there's nothing "wrong" with the data representation in this study.  Perhaps all samples could have been described as type=pool for consistency but it's not a big deal anyway. Also, they are very "abstract" samples.

The second study has a smaller number of assays with regular assay.counts - e.g. 48, 76. The sample.type looks like a mis-curation.

Conclusion: a large minority of studies/assays don't have assay.count. These aren't necessarily older studies. A careful user would want to filter these out.

**Comment by bobular** [comment]
And to summarise for the **Sample** entity

The only time we ever care about the sample.specimen_count is when it's an unbiased count from routine surveillance.  If 100 mosquitoes are tested for insecticide resistance, that goes in assay.number_of_input_specimens_for_quantitative_assay.

The next export will use the term POPBIO_8000017 `unbiased specimen count` for this. Name can be tweaked. Definition is currently: `The number of specimens collected during routine, unbiased surveillance.`

The variable will only be used when the collection effort is known (collection duration in days) and the number of traps is known (though that will default to 1 in exported data, and be a required variable in future curated data).

It will be the only Plan D count variable for the Sample entity.

**Comment by bobular** [comment]
Also to summarise - I'm not changing the sample type values at the moment.

I will be introducing new specimen count variables, and doing some clean-up as outlined above and in https://veupathdb.atlassian.net/wiki/spaces/WG/pages/315392001/Final+assault

**Comment by bobular** [comment]
Plan D for samples only applies to surveillance samples and these are the only ones with sample count which has been renamed "unbiased specimen count" and will be the only Plan D count for now.
