### ISSUE TITLE
Map: Remove studies representing sample types which aren't individual or pooled specimens

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#69]
There are a couple of sample types which don't represent wild caught specimens. There is a concern that these are not comparable to the rest of the data in the megastudy. Should consider removing them, or alternatives.

**Comment by d-callan** [comment]
We will remove them! This includes sample types of `population', 'laboratory-based population', and 'cultured cell'

**Comment by bobular** [comment]
Not necessarily removed from a "signposting megastudy" which I continue to think about how best to implement

**Comment by steve-fischer-200** [comment]
Remove

- tissue cell cultures
- lab tissue

**Comment by bobular** [comment]
Sarah removed the lion's share of these in the final Chado-based remediations prior to the b64 export.

If there are any left we can remove prior to loading or megastudy formation.

**Comment by bobular** [comment]
Done. Though there's a new kid on the block: "surveillance" type samples.
