### ISSUE TITLE
Map: multi-filter and collection annotations to wide data

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#73]
We have a related ticket [here](https://github.com/VEuPathDB/EdaLoadingIssues/issues/72).. but the idea is that things like pathogen presence/ prevalence will very likely be reshaped from tall to wide (meaning there will be multiple presence/ prevalence variables for different pathogens). Once this is done we need to make sure all pathogen presence variables are annotated appropriately so that they show as a multi-filter when filtering and are recognized as a collection available for use in the map markers + floating plots.

im adding @danicahelb to the ticket, in the hope that her experience annotating terms for clinepi will be helpful.

**Comment by bobular** [comment]
This is hopefully done here https://github.com/VEuPathDB/ApiCommonData/blob/eda_megastudy/Load/ontology/General/collections/popbio.yaml
