### ISSUE TITLE
Map: Reorganize variable tree/ categories to better accomodate tall to wide data reshaping

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#74]
see related tickets https://github.com/VEuPathDB/EdaLoadingIssues/issues/73 and https://github.com/VEuPathDB/EdaLoadingIssues/issues/72.

once the data for things like pathogen presence are wide well have a lot of related variables like pathogen X presence, pathogen Y presence. well also likely have variables like pathogen X prevalence and pathogen Y prevalence as well. These could be organized something like the following as a trivial ex to improve clarity:

**Pathogen Presence**
  -Pathogen X
  -Pathogen Y

**Pathogen Prevalence**
  -Pathogen X
  -Pathogen Y

**Comment by bobular** [comment]
Already done for Maine ticks wide reformatting.

**Comment by bobular** [comment]
Done now for all pathogens. Insecticide resistance still needs doing.

**Comment by bobular** [comment]
Done in https://github.com/VEuPathDB/ApiCommonData/pull/30 (duplicate issue I think)
