### ISSUE TITLE
Map: Identify what all variables need to go from tall to wide representations

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/EdaLoadingIssues#75]
We have data like pathogen presence in the popbio megastudy which we have decided should be reshaped from tall to wide. This isnt the only case though. @danicahelb had identified at least one place in wwarn where wed like to do the same. I think we should try to document here all instances we are aware of and identify whether they are needed for the tick qo in sept or for a beta release of the sam w the popbio megastudy.

see related ticket https://github.com/VEuPathDB/EdaLoadingIssues/issues/72

**Comment by bobular** [comment]
It was just pathogen assay results and genotypes.
Insecticide resistance would be way too wide.
