### ISSUE TITLE
Visualization: India ICEMR Fever Surveillance 'time since enrollment' vocabulary contains leading 0s

### ISSUE THREAD

**Issue by aaronwlsong** [VEuPathDB/EdaLoadingIssues#8]
In India ICEMR Fever Surveillance study, for some compatible variables,  the box plot has error page.

For example, when x="time since enrollment", y= any var, the webpage of visualization is down saying "something went wrong", and need to restart from homepage.
 
![image](https://user-images.githubusercontent.com/61077845/134980627-18d69fb1-cd0b-4874-af1a-49299f67c417.png)

**Comment by bobular** [comment]
This variable now works for barplot, boxplot and scatterplot

![image](https://user-images.githubusercontent.com/308639/135861445-717c09fa-cc5c-4898-98a9-d2f1662fb9ce.png)

Histogram is giving a 500 error.  I have seen this for other quasi-categorical integer variables.  I will see if there's another ticket for that, and if not, raise one.

**Comment by bobular** [comment]
Closing this, but maybe note that "Malaria diagnoses in the past year count" (same study) also has some leading zeroes in the vocabulary, but this does not seem to cause any issues (barplot response doesn't return any leading zeroes).

See also (time since enrolment is an integer-categorical variable)
https://github.com/VEuPathDB/EdaNewIssues/issues/160

**Comment by aaronwlsong** [comment]
Tested in the same study, seems the issue still exist.

**Comment by jaycolin** [comment]
Checked the database. Vocabulary for 'Time since enrollment' has no leading zeros. In 'Browse and subset' the values are displayed accurately (4,6,7,8). Works in box plot, scatter plot, and bar plot, but histogram never loads.

**Comment by dmfalke** [comment]
This specific example appears to be working on qa.clinepidb.org now. There is a more resilient solution covered in https://github.com/VEuPathDB/web-eda/issues/508, so moving this to complete.
